services:
  - type: web
    name: job-recommender
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: PORT
        value: 10000
    plan: free
